### ISSUE TITLE
Missing dimensions in logo_dimensions

### ISSUE THREAD

**Issue by zcohenld** [VoronDesign/Voron-Extras#10]
Out of curiosity I used the Logo_Dimensions.png file to create the logo in SolidWorks and it appears to be missing a dimension. You can make the entire logo with the given dimensions except for the angle of the slanted lines. You need either the angle to another line or another linear dimension between two of the endpoints of an angled line to infer the angle.

**Comment by nemgrea** [comment]
The angle of the stripes is perpendicular to the edges of the outer shape.

So 60deg from vertical

**Comment by zcohenld** [comment]
I wouldn't say this is closed since the file has not been updated. While it may look perpendicular, ISO/AMSE drafting standards are pretty clear in that drawings should not have any assumptions in them such as something being perpendicular when the lines aren't connecting.
